services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api_gateway
      dockerfile: ./dockerfile
    restart: "on-failure"
    depends_on:
      - redis
    ports:
      - 8000:8000
    networks:
      - app-network

  moderation-service:
    build:
      context: ./moderation_service
      dockerfile: ./dockerfile.service
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    networks:
      - app-network

  mock-server:
    build:
      context: ./mock_server
      dockerfile: ./dockerfile
    ports:
      - "8003:8003"
    networks:
      - app-network

  worker:
    build:
      context: ./moderation_service
      dockerfile: ./dockerfile.worker
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    restart: "always"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
